SET SERVEROUTPUT ON;
---EJERCICIO7.1---
CREATE OR REPLACE TYPE TCODIGOPOSTAL AS OBJECT(
    PROVINCIA NUMBER(2),
    LOCALIDAD NUMBER(3)
);

CREATE OR REPLACE TYPE TDOMICILIO AS OBJECT(
    TIPOVIA VARCHAR2(30),
    NOBREVIA VARCHAR2(30),
    NUMERO NUMBER(3),
    RESTODOMICILIO VARCHAR2(40)
);

CREATE OR REPLACE TYPE TNOMBRECOMPLETO AS OBJECT(
    NOMBRE VARCHAR2(30),
    PRAPELLIDO VARCHAR2(30),
    SGAPELLIDO VARCHAR2(30)
);

CREATE OR REPLACE TYPE DATOSPERSONALES AS OBJECT(
    CODIGODP NUMBER(3),
    NOMBRECOMPLETO TNOMBRECOMPLETO,
    DOMICILIO TDOMICILIO,
    CODIGOPOSTAL TCODIGOPOSTAL,
    FECHANACIMIENTO DATE
);