SET SERVEROUTPUT ON;
----EJERCICIO 7.5----
CREATE OR REPLACE TYPE PERSONA2 AS OBJECT(
    NOMBRE VARCHAR2(30),
    EDAD NUMBER(2),
    CONSTRUCTOR FUNCTION PERSONA2(NOMBRE VARCHAR2, EDAD NUMBER)RETURN SELF AS RESULT
);

CREATE OR REPLACE TYPE BODY PERSONA2 AS
CONSTRUCTOR FUNCTION PERSONA2(
    NOMBRE VARCHAR2,
    EDAD NUMBER
)RETURN SELF AS RESULT IS
    BEGIN
        SELF.NOMBRE:=NOMBRE;
        SELF.EDAD:=EDAD;
        RETURN;
    END;
END;

DECLARE
    vDANIEL PERSONA2;
BEGIN
    vDANIEL:= NEW PERSONA2('DANIEL', 18);
    DBMS_OUTPUT.PUT_LINE(vDANIEL.NOMBRE||' TIENE '||vDANIEL.EDAD||' AÑOS');
END;