SET SERVEROUTPUT ON;
---EJERCICIO7.3---
SET SERVEROUTPUT ON;
CREATE OR REPLACE TYPE TOBJCODIGOPOSTAL AS OBJECT(
    CODPROV NUMBER(2),
    CODLOCALIDAD NUMBER(3),
    MEMBER PROCEDURE PROCEDIMIENTO(P_CODPROV NUMBER, P_CODLOCALIDAD NUMBER)
);

CREATE OR REPLACE TYPE BODY TOBJCODIGOPOSTAL AS 
    MEMBER PROCEDURE PROCEDIMIENTO(P_CODPROV NUMBER, P_CODLOCALIDAD NUMBER) IS
    BEGIN
    CODPROV:=P_CODPROV;
    CODLOCALIDAD:=P_CODLOCALIDAD;
    END PROCEDIMIENTO;
END;

DECLARE
    COD1 TOBJCODIGOPOSTAL := TOBJCODIGOPOSTAL(47,012);
BEGIN
    DBMS_OUTPUT.PUT_LINE(COD1.CODLOCALIDAD);
    COD1.PROCEDIMIENTO(37,034);
    DBMS_OUTPUT.PUT_LINE(COD1.CODLOCALIDAD);
END;
--
CREATE OR REPLACE TYPE TOBJDOMICILIO AS OBJECT(
    TIPOVIA VARCHAR2(30),
    NOBREVIA VARCHAR2(30),
    NUMERO NUMBER(2),
    RESTODOMICILIO VARCHAR2(40),
    MEMBER PROCEDURE PROCEDIMIENTO2(P_TIPOVIA VARCHAR2, P_NOMBREVIA VARCHAR2, P_NUMERO NUMBER, P_RESTODOMICILIO VARCHAR2)
);

CREATE OR REPLACE TYPE BODY TOBJDOMICILIO AS 
    MEMBER PROCEDURE PROCEDIMIENTO2(P_TIPOVIA VARCHAR2, P_NOMBREVIA VARCHAR2, P_NUMERO NUMBER, P_RESTODOMICILIO VARCHAR2) IS
    BEGIN
     TIPOVIA:=P_TIPOVIA;
     NOBREVIA:=P_NOMBREVIA;
     NUMERO:=P_NUMERO;
     RESTODOMICILIO:=P_RESTODOMICILIO;
    END PROCEDIMIENTO2;
END;

DECLARE
 COD2 TOBJDOMICILIO := TOBJDOMICILIO('AVENIDA', 'JUAN CARLOS I', 33, '2ºD');
BEGIN
    DBMS_OUTPUT.PUT_LINE(COD2.TIPOVIA);
    DBMS_OUTPUT.PUT_LINE(COD2.NOBREVIA);
    DBMS_OUTPUT.PUT_LINE(COD2.RESTODOMICILIO);
    COD2.PROCEDIMIENTO2('CALLE', 'JUAN CARLOS II', 5, '2ºD');
    DBMS_OUTPUT.PUT_LINE(COD2.NOBREVIA);
    DBMS_OUTPUT.PUT_LINE(COD2.NUMERO);
    
END;
--
CREATE OR REPLACE TYPE TOBJNOMBRE AS OBJECT(
     NOMBRE VARCHAR2(30),
    PRAPELLIDO VARCHAR2(30),
    SGAPELLIDO VARCHAR2(30),
    MEMBER PROCEDURE PROCEDIMIENTO3(P_NOMBRE VARCHAR2, P_PRAPELLIDO VARCHAR2, P_SGAPELLIDO VARCHAR2)
);

CREATE OR REPLACE TYPE BODY TOBJNOMBRE AS 
    MEMBER PROCEDURE PROCEDIMIENTO3(P_NOMBRE VARCHAR2, P_PRAPELLIDO VARCHAR2, P_SGAPELLIDO VARCHAR2) IS
    BEGIN
     NOMBRE:=P_NOMBRE;
     PRAPELLIDO:=P_PRAPELLIDO;
     SGAPELLIDO:=P_SGAPELLIDO;
    END PROCEDIMIENTO3;
END;

DECLARE
 COD3 TOBJNOMBRE := TOBJNOMBRE('DANIEL', 'COBO', 'GUERRERO');
BEGIN
    DBMS_OUTPUT.PUT_LINE(COD3.NOMBRE);
    DBMS_OUTPUT.PUT_LINE(COD3.PRAPELLIDO);
    DBMS_OUTPUT.PUT_LINE(COD3.SGAPELLIDO);
    COD3.PROCEDIMIENTO3('ADRIANA', 'COBO', 'GUERRERO');
    DBMS_OUTPUT.PUT_LINE(COD3.NOMBRE);
    DBMS_OUTPUT.PUT_LINE(COD3.PRAPELLIDO);
    
END;
--
CREATE OR REPLACE TYPE TOBJDATOS AS OBJECT(
    CODIGODP NUMBER(3),
    NOMBRECOMPLETO TNOMBRECOMPLETO,
    DOMICILIO TDOMICILIO,
    CODIGOPOSTAL TCODIGOPOSTAL,
    FECHANACIMIENTO DATE,
    MEMBER PROCEDURE PROCEDIMIENTO4(P_CODIGODP NUMBER, P_NOMBRECOMPLETO TNOMBRECOMPLETO, P_DOMICILIO TDOMICILIO, P_CODIGOPOSTAL TCODIGOPOSTAL, P_FECHANACIMIENTO DATE)
);

CREATE OR REPLACE TYPE BODY TOBJDATOS AS 
    MEMBER PROCEDURE PROCEDIMIENTO4(P_CODIGODP NUMBER, P_NOMBRECOMPLETO TNOMBRECOMPLETO, P_DOMICILIO TDOMICILIO, P_CODIGOPOSTAL TCODIGOPOSTAL, P_FECHANACIMIENTO DATE) IS
    BEGIN
     CODIGODP:=P_CODIGODP;
     NOMBRECOMPLETO:=P_NOMBRECOMPLETO;
     DOMICILIO:=P_DOMICILIO;
     CODIGOPOSTAL:=P_CODIGOPOSTAL;
     FECHANACIMIENTO:=P_FECHANACIMIENTO;
    END PROCEDIMIENTO4;
END;

DECLARE
    NOM4 TNOMBRECOMPLETO:= TNOMBRECOMPLETO('DANIEL', 'COBO', 'GUERRERO');
    DOM4 TDOMICILIO:= TDOMICILIO('AVENIDA', 'JUAN CARLOS I', 33, '2ºD');
    CODPOSTAL4 TCODIGOPOSTAL:= TCODIGOPOSTAL(41,001);
    COD4 TOBJDATOS := TOBJDATOS(111,NOM4,DOM4,CODPOSTAL4,'23/07/1973');
    NOMBRE4 TNOMBRECOMPLETO:= TNOMBRECOMPLETO('DANIEL', 'COBO', 'GUERRERO');
BEGIN
    DBMS_OUTPUT.PUT_LINE(COD4.CODIGODP);
    DBMS_OUTPUT.PUT_LINE(COD4.NOMBRECOMPLETO);
    DBMS_OUTPUT.PUT_LINE(COD4.DOMICILIO);
    COD4.PROCEDIMIENTO4(121,NOMBRE4,DOM4,CODPOSTAL4,'23/07/1973');
    DBMS_OUTPUT.PUT_LINE(COD4.NOMBRECOMPLETO);
    DBMS_OUTPUT.PUT_LINE(COD4.CODIGOPOSTAL);
    
END;