SET SERVEROUTPUT ON;
---EJERCICIO7.4
CREATE OR REPLACE TYPE PERSONA AS OBJECT(
    vDNI VARCHAR2(9),
    vNOMBRE VARCHAR2(30),
    vAPELLIDOS VARCHAR2(30),
    vFECHANACIOMIENTO DATE,
    MEMBER FUNCTION MUESTRAEDAD RETURN NUMBER
);
CREATE OR REPLACE TYPE BODY PERSONA AS
MEMBER FUNCTION MUESTRAEDAD RETURN NUMBER IS
        vEDAD NUMBER;
    BEGIN
        --METODO QUE EXTRAE EL AÑO POR LA FECHA DEL SYSDATE Y LE RESTA EL AÑO QUE EXTRAE DE LA VARIABLE vFECHANACIMIENTO, YA QUE SINO DARIA UNA EDAD NEGATIVA.
        vEDAD := EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM SELF.vFECHANACIOMIENTO);
        RETURN vEDAD;
    END MUESTRAEDAD;
END;