SET SERVEROUTPUT ON;
-------EJERCICIO7.8-----
CREATE OR REPLACE TYPE EMPLEADO AS OBJECT(
    DNI VARCHAR(9),
    NOMBRE VARCHAR2(30),
    APELLIDO1 VARCHAR2(30),
    APELLIDO2 VARCHAR2(30),
    TELEFONO NUMBER(9)
)NOT FINAL;

CREATE OR REPLACE TYPE INSPECTOR UNDER EMPLEADO (
    ESPECIALIDAD VARCHAR2(30)
);

CREATE OR REPLACE TYPE POLICIA UNDER EMPLEADO (
    CATEGORIA VARCHAR2(30),
    SALARIOBASE NUMBER,
    MEMBER FUNCTION CALCULARSALARIO(SALARIOBASE NUMBER)RETURN NUMBER
);

CREATE OR REPLACE TYPE BODY POLICIA AS 
    MEMBER FUNCTION CALCULARSALARIO(SALARIOBASE NUMBER) RETURN NUMBER IS
    SALARIOFINAL NUMBER;
    BEGIN
        IF SELF.CATEGORIA='LOCAL' THEN
            SALARIOFINAL:=SALARIOBASE*1.05;
        ELSIF SELF.CATEGORIA='NACIONAL' THEN
            SALARIOFINAL:=SALARIOBASE*1.15;
        ELSIF SELF.CATEGORIA='OPERACIONES ESPECIALES' THEN
            SALARIOFINAL:=SALARIOBASE*1.20;
        END IF;
        RETURN SALARIOFINAL;
    END;
END;
CREATE TABLE POLICIAS OF POLICIA;
CREATE TABLE RESPONSABLES OF INSPECTOR;