SET SERVEROUTPUT ON;
CREATE OR REPLACE TYPE TDATOSPERSONALES AS OBJECT(
    CODIGODP NUMBER(3),
    NOMBRECOMPLETO TNOMBRECOMPLETO,
    DOMICILIO TDOMICILIO,
    CODIGOPOSTAL TCODIGOPOSTAL,
    FECHANACIMIENTO DATE,
    MEMBER PROCEDURE PROCEDIMIENTO(P_CODIGODP NUMBER, P_NOMBRECOMPLETO TNOMBRECOMPLETO, P_DOMICILIO TDOMICILIO, P_CODIGOPOSTAL TCODIGOPOSTAL, P_FECHANACIMIENTO DATE)
)NOT FINAL;

CREATE OR REPLACE TYPE BODY TDATOSPERSONALES AS
    MEMBER PROCEDURE PROCEDIMIENTO(P_CODIGODP NUMBER, P_NOMBRECOMPLETO TNOMBRECOMPLETO, P_DOMICILIO TDOMICILIO, P_CODIGOPOSTAL TCODIGOPOSTAL, P_FECHANACIMIENTO DATE) IS
    BEGIN
    CODIGODP:=P_CODIGODP;
    NOMBRECOMPLETO:=P_NOMBRECOMPLETO;
    DOMICILIO:=P_DOMICILIO;
    CODIGOPOSTAL:=P_CODIGOPOSTAL;
    FECHANACIMIENTO:=P_FECHANACIMIENTO;
    END 
END;

CREATE TYPE PROFESOR UNDER TDATOSPERSONALES (
    FECHAINCORPORACION DATE
);

CREATE TYPE CALIFICACIONES AS OBJECT(
    CALIFICACIONUNO NUMBER,
    CALIFICACIONDOS NUMBER,
    CALIFICACIONTRES NUMBER,
    CALIFICACIONCUATRO NUMBER
);

CREATE TYPE ALUMNO UNDER TDATOSPERSONALES (
    vCALIFICACIONES CALIFICACIONES
);

